### PR TITLE
Stored procedure changing

### PR DESCRIPTION
**Pull request by Expecho**
Proposed fix for issue https://github.com/mspnp/semantic-logging/issues/34

It adds support for setting the stored procedure using a parameter in the sink configuration. Applies to the SqlDatabaseSink

### CODE REVIEW

**Comment by mekoda** [comment]
Thanks for your contribution! Evaluating it right now.

**Comment by mekoda** [comment]
Thanks again for your contribution! 

I'm afraid the pull request doesn't work in an out-of-process scenario. An error is thrown during the loading of the configuration file; however, this can be fixed by adding the new attribute on the XSD file (SemanticLogging-svc.xsd). Moreover, you can fix this and update the PR.

**Comment by Expecho** [comment]
Gastón N. Charkiewicz schreef op 05.04.2016 18:27: 

> Thanks again for your contribution! 
> 
> I'm afraid the pull request doesn't work in an out-of-process scenario. An error is thrown during the loading of the configuration file; however, this can be fixed by adding the new attribute on the XSD file (SemanticLogging-svc.xsd). Moreover, you can fix this and update the PR. 
> 
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub [1]

Hi, 

I've fixed it accordingly and tested it locally. I've updated the PR. 

Best regards, 

Peter 

 

Links:
------
[1]
https://github.com/mspnp/semantic-logging/pull/36#issuecomment-205884018

**Comment by arambarri** [comment]
Hi @Expecho,

Thanks for your job.

We kindly request you format the last file changed and update the PR in order to be ready for merging (control+k+d).

**Comment by Expecho** [comment]
Hi @arambarri , file should be ok now..

**Pull request merged**
